# Generated by Django 5.0.6 on 2026-07-30 18:59

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood', models.CharField(choices=[('happy', '😊 Happy'), ('neutral', '😐 Neutral'), ('sad', '😢 Sad'), ('angry', '😡 Angry'), ('anxious', '😰 Anxious'), ('tired', '😴 Tired'), ('excited', '😍 Excited'), ('depressed', '😞 Depressed')], max_length=20)),
                ('intensity', models.PositiveSmallIntegerField(help_text='Self-reported intensity of the mood, 1 (mild) to 10 (extreme).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('entry_date', models.DateField(db_index=True)),
                ('entry_time', models.TimeField()),
                ('notes', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'Mood Entry',
                'verbose_name_plural': 'Mood Entries',
                'db_table': 'mood_entries',
                'ordering': ['-entry_date', '-entry_time'],
            },
        ),
    ]
