# Generated by Django 5.0.6 on 2026-07-30 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('reason_for_visit', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Counselor/admin-facing notes.')),
                ('cancellation_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
