# Generated by Django 5.0.6 on 2026-08-08 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('mood', models.CharField(blank=True, choices=[('happy', '😊 Happy'), ('neutral', '😐 Neutral'), ('sad', '😢 Sad'), ('angry', '😡 Angry'), ('anxious', '😰 Anxious'), ('tired', '😴 Tired'), ('excited', '😍 Excited'), ('depressed', '😞 Depressed')], max_length=20)),
                ('entry_date', models.DateField(db_index=True)),
                ('is_flagged', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'db_table': 'journal_entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'db_table': 'journal_tags',
                'ordering': ['name'],
            },
        ),
    ]
