# Generated by Django 5.0.6 on 2026-08-03 11:36

from django.db import migrations, models


def delete_stale_tokens(apps, schema_editor):
    """
    Old rows hold long link-style tokens (up to 255 chars); the AlterField
    below narrows the column to 6 chars for OTP codes, which Postgres
    rejects outright if any existing value is longer. These are one-time,
    short-lived auth artifacts with no lasting value, so it's safe to just
    clear them — anyone mid-flow simply requests a fresh code.
    """
    apps.get_model('users', 'EmailVerificationToken').objects.all().delete()
    apps.get_model('users', 'PasswordResetToken').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(delete_stale_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
