# Generated by Django 5.0.6 on 2026-08-04 14:55 (rewritten — see note below)

from django.db import migrations, models


def delete_stale_tokens(apps, schema_editor):
    """
    Existing rows hold long link-style tokens (up to 255 chars); the
    AlterField below narrows the column to 6 chars for OTP codes, which
    Postgres rejects outright if any existing value is longer. These are
    one-time, short-lived auth artifacts with no lasting value, so it's
    safe to just clear them — anyone mid-flow simply requests a fresh
    code. (Same fix needed the first time this column was narrowed —
    see 0002_fix_token_column_drift's history.)
    """
    apps.get_model('users', 'EmailVerificationToken').objects.all().delete()
    apps.get_model('users', 'PasswordResetToken').objects.all().delete()


def drop_leftover_unique_and_index(apps, schema_editor):
    """
    Postgres-only pre-step, needed before the AlterFields below run.

    The *original* OTP migration (deleted when OTP was reverted) already
    ran this exact unique -> plain-index transition on Render once:
    dropped the 0001 unique constraint on `token` and created a plain
    btree index. Deleting that migration file only erased Django's
    record of the transition, not the transition itself — the index it
    created is still sitting in the database. Django computes index
    names deterministically from table+column (not from migration
    history), so the AlterField below tries to (re)create that exact
    same name and fails with "relation already exists" unless it's
    cleared first. sqlite/test databases never went through the deleted
    migration, so there's nothing to do there.
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in ("email_verification_tokens", "password_reset_tokens"):
            cursor.execute(
                "SELECT conname FROM pg_constraint WHERE conrelid = %s::regclass AND contype = 'u'",
                [table],
            )
            for (conname,) in cursor.fetchall():
                cursor.execute(f'ALTER TABLE {table} DROP CONSTRAINT IF EXISTS "{conname}"')

            cursor.execute(
                "SELECT indexname FROM pg_indexes WHERE tablename = %s AND indexname LIKE %s",
                [table, f"{table}_token_%"],
            )
            for (indexname,) in cursor.fetchall():
                cursor.execute(f'DROP INDEX IF EXISTS "{indexname}"')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fix_token_column_drift'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(delete_stale_tokens, migrations.RunPython.noop),
        migrations.RunPython(drop_leftover_unique_and_index, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
