# Generated by Django 5.0.6 on 2026-07-30 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('physical_activity', 'Physical Activity'), ('mindfulness', 'Mindfulness / Meditation'), ('breathing', 'Breathing Exercise'), ('sleep', 'Sleep'), ('nutrition', 'Nutrition / Hydration'), ('social', 'Social Connection'), ('self_care', 'Self-care'), ('professional_help', 'Professional Help'), ('entertainment', 'Entertainment / Media'), ('education', 'Wellness Article / Education')], max_length=30)),
                ('source', models.CharField(choices=[('mood', 'Mood'), ('journal', 'Journal'), ('assessment', 'Assessment'), ('chat', 'Chat'), ('system', 'System / Scheduled')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('physical_activity', 'Physical Activity'), ('mindfulness', 'Mindfulness / Meditation'), ('breathing', 'Breathing Exercise'), ('sleep', 'Sleep'), ('nutrition', 'Nutrition / Hydration'), ('social', 'Social Connection'), ('self_care', 'Self-care'), ('professional_help', 'Professional Help'), ('entertainment', 'Entertainment / Media'), ('education', 'Wellness Article / Education')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_url', models.URLField(blank=True)),
                ('trigger_conditions', models.JSONField(blank=True, default=dict, help_text='e.g. {"mood_in": ["sad", "depressed"], "min_stress_score": 0.6}')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'recommendation_templates',
            },
        ),
    ]
