# Generated by Django 5.0.6 on 2026-07-30 18:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predicted_for_date', models.DateField()),
                ('predicted_mood', models.CharField(choices=[('happy', '😊 Happy'), ('neutral', '😐 Neutral'), ('sad', '😢 Sad'), ('angry', '😡 Angry'), ('anxious', '😰 Anxious'), ('tired', '😴 Tired'), ('excited', '😍 Excited'), ('depressed', '😞 Depressed')], max_length=20)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('based_on_window_days', models.PositiveSmallIntegerField(default=14)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mood_predictions',
                'ordering': ['-predicted_for_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('detection_source', models.CharField(choices=[('journal', 'Journal Entry'), ('chat', 'Chat Message'), ('assessment', 'Assessment')], max_length=20)),
                ('triggered_phrases', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('resources_shown_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'risk_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('stress_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('anxiety_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('burnout_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('depression_indicator_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('keywords', models.JSONField(default=list, help_text='Salient keywords/phrases extracted from the text.')),
                ('model_version', models.CharField(help_text='Hugging Face model id + version used.', max_length=100)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sentiment_results',
            },
        ),
        migrations.CreateModel(
            name='WellnessScoreSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_date', models.DateField(db_index=True)),
                ('overall_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('mood_component', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('journal_component', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('assessment_component', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('sleep_component', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('activity_component', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('chat_sentiment_component', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'wellness_score_snapshots',
                'ordering': ['-score_date'],
            },
        ),
        migrations.CreateModel(
            name='EmotionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('dominant_emotion', models.CharField(choices=[('joy', 'Joy'), ('fear', 'Fear'), ('sadness', 'Sadness'), ('anger', 'Anger'), ('love', 'Love'), ('surprise', 'Surprise'), ('optimism', 'Optimism'), ('disappointment', 'Disappointment')], max_length=20)),
                ('scores', models.JSONField(default=dict, help_text='Full distribution, e.g. {"joy": 0.72, "sadness": 0.05, ...}')),
                ('model_version', models.CharField(max_length=100)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'emotion_results',
            },
        ),
    ]
