# Generated by Django 5.0.6 on 2026-08-08 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0002_initial'),
        ('journals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_results', to='journals.journalentry'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['user', 'risk_level'], name='risk_assess_user_id_5130f7_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['risk_level', 'created_at'], name='risk_assess_risk_le_ceeb7a_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentresult',
            index=models.Index(fields=['journal_entry', 'created_at'], name='sentiment_r_journal_b98c73_idx'),
        ),
    ]
