# Generated by Django 5.0.6 on 2026-08-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed'), ('email_verified', 'Email Verified'), ('profile_updated', 'Profile Updated'), ('data_exported', 'Data Exported'), ('permission_denied', 'Permission Denied'), ('account_locked', 'Account Locked'), ('account_deleted', 'Account Deleted'), ('admin_action', 'Administrative Action'), ('risk_detected', 'Crisis/Risk Language Detected')], max_length=50),
        ),
    ]
