# Generated by Django 5.0.6 on 2026-07-30 18:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=500)),
                ('options', models.JSONField(default=list, help_text='e.g. [{"value": 0, "label": "Not at all"}, {"value": 3, "label": "Nearly every day"}]')),
            ],
            options={
                'db_table': 'assessment_questions',
                'ordering': ['assessment_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('severity', models.CharField(choices=[('minimal', 'Minimal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('moderately_severe', 'Moderately Severe'), ('severe', 'Severe')], max_length=20)),
                ('interpretation', models.TextField(help_text='Human-readable, non-diagnostic interpretation text shown to the user.')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assessment_results',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('phq9', 'PHQ-9 (Depression)'), ('gad7', 'GAD-7 (Anxiety)'), ('stress', 'Perceived Stress Scale'), ('burnout', 'Burnout Assessment'), ('self_esteem', 'Rosenberg Self-Esteem Scale')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('max_score', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'assessment_types',
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_value', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='assessments.assessmentquestion')),
            ],
            options={
                'db_table': 'assessment_answers',
            },
        ),
    ]
