# Generated by Django 5.0.6 on 2026-07-30 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.assessmentresult'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='assessments.assessmenttype'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessmenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentanswer',
            unique_together={('result', 'question')},
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['user', 'assessment_type', 'taken_at'], name='assessment__user_id_62a62d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentquestion',
            unique_together={('assessment_type', 'order')},
        ),
    ]
