# Generated by Django 5.0.6 on 2026-07-30 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(help_text="e.g. 'user_suspended', 'journal_report_actioned'.", max_length=100)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'admin_action_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('mental_health', 'Mental Health Summary')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], max_length=5)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'generated_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
