# Generated by Django 5.0.6 on 2026-08-08 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(help_text="e.g. 'user_suspended', 'risk_alert_reviewed'.", max_length=100)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'admin_action_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
