# Generated by Django 5.0.6 on 2026-07-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='librechat_message_id',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='librechat_conversation_id',
        ),
    ]
