# Generated by Django 5.0.6 on 2026-07-30 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('podcast', 'Podcast'), ('meditation', 'Meditation'), ('breathing_exercise', 'Breathing Exercise'), ('emergency', 'Emergency Resource')], max_length=30)),
                ('body', models.TextField(blank=True, help_text='Full article body (for resource_type=article).')),
                ('external_url', models.URLField(blank=True, help_text='Video/podcast link, for resource_type in (video, podcast).')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Resource Categories',
                'db_table': 'resource_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(db_index=True, help_text="ISO 3166-1 alpha-2, e.g. 'US', 'GH'.", max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('sms_number', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_24_7', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
            ],
            options={
                'db_table': 'emergency_resources',
                'indexes': [models.Index(fields=['country_code'], name='emergency_r_country_7eeda8_idx')],
            },
        ),
    ]
