# Generated by Django 5.0.6 on 2026-08-08 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.resourcecategory'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type', 'is_published'], name='resources_resourc_1b6e23_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['category'], name='resources_categor_3512bc_idx'),
        ),
    ]
