const SECTIONS = [
  {
    title: "Purpose",
    body: "This app is a bounded, non-diagnostic mood and journaling log for adults (18+). It exists to help you keep a private record of your mood and journal entries, with one automated feature: a tentative sentiment label (positive/negative/neutral) generated by a text-classification model. It is not a mental health platform, not therapy, and not a substitute for professional care.",
  },
  {
    title: "What we collect",
    body: "A pseudonym you choose (shown throughout the app instead of your real name), a recovery email (used only for login and account recovery, never shown to other users), your password (stored as a salted hash, never in plain text), mood entries, journal entries, and the tentative sentiment label generated for each journal entry along with whether you accepted, rejected, or corrected it.",
  },
  {
    title: "Storage & access",
    body: "Data is stored in our production database and is not shared with third parties or used to train external models. Only you can see your journal and mood entries. Administrators can see account-level information (email, pseudonym, role, account status) to operate the platform, and can see risk-tier flags raised by the crisis-phrase detector — never the journal text that triggered them.",
  },
  {
    title: "The sentiment label, in plain terms",
    body: "Every journal entry gets a tentative label from a classical machine-learning model (TF-IDF + logistic regression, trained on a public benchmark dataset). It estimates text polarity only — it is never presented as an emotion, diagnosis, or severity score, and you can accept, reject, or correct it at any time.",
  },
  {
    title: "Crisis-phrase detection",
    body: "A separate, deterministic (non-AI) rule-based check scans journal entries for a fixed list of crisis-related phrases. If matched, you're shown a support-resource card. This check never claims to monitor you in real time, never notifies anyone on your behalf, and never claims to have contacted emergency services. Only the risk tier is logged — the matched text itself is never stored.",
  },
  {
    title: "Retention",
    body: "Your data is retained for as long as your account exists. There is no automatic expiry beyond that — you control retention by editing, deleting individual entries, or deleting your account entirely.",
  },
  {
    title: "Deletion",
    body: "You can delete any individual journal entry at any time — this is a real, permanent deletion, not a soft-hide. You can also delete your entire account from Settings → Account & data, which requires your password and immediately and permanently removes your account and everything tied to it. This cannot be undone or recovered.",
  },
  {
    title: "Not a diagnostic or emergency service",
    body: "This app does not diagnose any condition and is not a substitute for a licensed mental health professional. It cannot and does not monitor you in real time, and cannot contact emergency services on your behalf. If you are in crisis or in immediate danger, contact local emergency services or a crisis hotline directly.",
  },
];

export default function PrivacyNoticePage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <h1 className="text-4xl font-extrabold text-gray-900 dark:text-white">Privacy notice</h1>
      <p className="mt-3 text-gray-600 dark:text-gray-300">
        What this app collects, why, and how you can see or delete it.
      </p>

      <div className="mt-6 rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-800 dark:border-amber-700 dark:bg-amber-950/40 dark:text-amber-200">
        Not a substitute for professional care. If you're in crisis, contact local emergency services.
      </div>

      <div className="mt-10 space-y-8">
        {SECTIONS.map((s) => (
          <section key={s.title}>
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">{s.title}</h2>
            <p className="mt-2 text-sm leading-6 text-gray-600 dark:text-gray-300">{s.body}</p>
          </section>
        ))}
      </div>
    </div>
  );
}
